apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: clickhouse-prod
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/tracefox-ai/tfx-k8s.git
    targetRevision: HEAD
    path: helm/clickhouse
    helm:
      valueFiles:
        - values-prod.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: production
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true

