apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infrastructure
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default  # App of Apps uses default project (creates Applications in argocd namespace)
  source:
    repoURL: https://github.com/tracefox-ai/tfx-k8s.git
    targetRevision: HEAD
    path: argocd/apps/infrastructure
    directory:
      recurse: false
      exclude: 'app-of-apps.yaml'
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
